In [1]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# Generate an array of zeros
zeros_array = np.zeros((2, 3))
print("Zeros Array:\n", zeros_array)

# Generate an array of ones
ones_array = np.ones((3, 2))
print("Ones Array:\n", ones_array)

# Generate an array with a range of values
range_array = np.arange(0, 10, 2)
print("Range Array:", range_array)

# Generate a random array
random_array = np.random.rand(3, 3)
print("Random Array:\n", random_array)

# Perform element-wise operations
array_sum = array_1d + 5
print("Array after adding 5:", array_sum)

# Matrix multiplication
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
print("Matrix Product:\n", matrix_product)

# Transpose of a matrix
transpose_matrix = np.transpose(matrix_a)
print("Transpose of Matrix A:\n", transpose_matrix)

# Statistical operations
mean_value = np.mean(array_1d)
print("Mean of 1D Array:", mean_value)

std_deviation = np.std(array_1d)
print("Standard Deviation of 1D Array:", std_deviation)

# Reshape an array
reshaped_array = np.reshape(array_1d, (1, 5))
print("Reshaped Array:\n", reshaped_array)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range Array: [0 2 4 6 8]
Random Array:
 [[0.32679333 0.19428744 0.29936427]
 [0.32294434 0.03032896 0.71802515]
 [0.59302038 0.74128871 0.7954917 ]]
Array after adding 5: [ 6  7  8  9 10]
Matrix Product:
 [[19 22]
 [43 50]]
Transpose of Matrix A:
 [[1 3]
 [2 4]]
Mean of 1D Array: 3.0
Standard Deviation of 1D Array: 1.4142135623730951
Reshaped Array:
 [[1 2 3 4 5]]
